[project]
name = "randbats-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "advancedhtmlparser>=9.0.2",
    "parse>=1.20.2",
    "pydantic>=2.10.6",
]
